server:
  port: 8848

spring:
  datasource:
    url: jdbc:mysql://101.34.163.251:3306/andredb
    username: andre
    password: mysql@andre!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

wx:
  account:
    appid: wxdff70d172c26d965
    secret: f3cae9e6ab1ea13f247dbf9b626116ed
